name: mercado_pago_integration
description: >-
  MercadoPago Mobile Checkout Integration for android and ios. Easy to install, Easy to integrate, PCI compliance, Android Support, IOS Support. This project includes an example project using Mercado Pago Integration, checkout example folder. In case you need support contact the Caramel Point Developers Site.


homepage: https://github.com/caramelpoint/mercado_pago_integration
version: 0.0.4

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  mercadopago_sdk: ^1.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.caramelpoint.mercado_pago_integration
        pluginClass: MercadoPagoIntegrationPlugin
      ios:
        pluginClass: MercadoPagoIntegrationPlugin
