name: mercado_pago_integration
description: >-
  MercadoPago Mobile Checkout Integration for android and ios


homepage: https://github.com/caramelpoint/mercado_pago_integration
version: 0.0.3

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.caramelpoint.mercado_pago_integration
        pluginClass: MercadoPagoIntegrationPlugin
      ios:
        pluginClass: MercadoPagoIntegrationPlugin
