name: mercado_pago_integration
description: >-
  MercadoPago Mobile Checkout Integration for android and ios. Easy to install, Easy to integrate, Android Support, IOS Support.


homepage: https://github.com/caramelpoint/mercado_pago_integration
version: 1.1.8

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  mercadopago_sdk: ^1.2.0
  intl: ^0.17.0
  dartz: ^0.9.2
  equatable: ^1.2.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.caramelpoint.mercado_pago_integration
        pluginClass: MercadoPagoIntegrationPlugin
      ios:
        pluginClass: MercadoPagoIntegrationPlugin
